apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: operon
resources:
  - namespace.yaml
  - configuration.yaml
  - edge.yaml
  - operon-stream.yaml
  - kafka-trigger.yaml
  - agent-trigger.yaml
